
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.jade]
		enable_compat_jade = true

	[Compatibility.biomesoplenty]
		enable_compat_biomesoplenty = true
		#Whether sundamage should be applied to vampires in this biome or not
		disable_sundamage_ominous_woods = true

	[Compatibility.ctov]
		enable_compat_ctov = true

